# Bot catalog - English names only (avoids encoding issues on deploy).
# Amharic labels stay on the website.

PRODUCTS = [
    {"id": 1, "name": "Yirgacheffe Coffee Beans, 1kg", "cat": "Coffee & Tea", "price": 1380, "sale": None, "photo": "photos/1.jpg"},
    {"id": 18, "name": "Coffee Ceremony Tray Set", "cat": "Coffee & Tea", "price": 1500, "sale": None, "photo": None},
    {"id": 36, "name": "Roasted Coffee Beans, 1kg", "cat": "Coffee & Tea", "price": 1400, "sale": None, "photo": "photos/36.jpg"},
    {"id": 37, "name": "Ground Coffee, 250g", "cat": "Coffee & Tea", "price": 420, "sale": None, "photo": "photos/37.jpg"},
    {"id": 2, "name": "Traditional Clay Jebena", "cat": "Home & Kitchen", "price": 650, "sale": 550, "photo": None},
    {"id": 10, "name": "Electric Injera Mitad", "cat": "Home & Kitchen", "price": 3200, "sale": None, "photo": "photos/10.jpg"},
    {"id": 3, "name": "Habesha Kemis, Hand-Embroidered", "cat": "Apparel", "price": 2200, "sale": None, "photo": None},
    {"id": 6, "name": "Handwoven Shemma Scarf", "cat": "Apparel", "price": 480, "sale": None, "photo": None},
    {"id": 11, "name": "Handmade Leather Sandals", "cat": "Apparel", "price": 620, "sale": None, "photo": None},
    {"id": 15, "name": "Habesha Netela, Cotton Shawl", "cat": "Apparel", "price": 900, "sale": None, "photo": None},
    {"id": 4, "name": "Berbere Spice Blend, 200g", "cat": "Spices & Pantry", "price": 150, "sale": None, "photo": "photos/4.jpg"},
    {"id": 5, "name": "Mitmita Spice Blend, 150g", "cat": "Spices & Pantry", "price": 140, "sale": None, "photo": "photos/5.jpg"},
    {"id": 7, "name": "Ethiopian Cross Necklace, Silver", "cat": "Jewelry", "price": 950, "sale": 800, "photo": "photos/7.jpg"},
    {"id": 9, "name": "Wireless Earbuds", "cat": "Electronics", "price": 2600, "sale": 2100, "photo": "photos/9.jpg"},
    {"id": 16, "name": "USB-C Fast Charger, 20W", "cat": "Electronics", "price": 750, "sale": None, "photo": "photos/16.jpg"},
    {"id": 13, "name": "Amharic Children's Storybook Set", "cat": "Books & Paper", "price": 260, "sale": None, "photo": None},
    {"id": 14, "name": "Frankincense & Myrrh Set", "cat": "Home & Garden", "price": 180, "sale": None, "photo": None},
    {"id": 17, "name": "Woven Mesob Basket", "cat": "Home & Garden", "price": 1400, "sale": 1150, "photo": None},
    {"id": 19, "name": "Teff Flour, 5kg", "cat": "Grocery", "price": 620, "sale": None, "photo": "photos/19.jpg"},
    {"id": 20, "name": "Fresh Avocados, 1kg Bag", "cat": "Grocery", "price": 110, "sale": None, "photo": "photos/20.jpg"},
    {"id": 21, "name": "Shiro Powder, 500g", "cat": "Grocery", "price": 170, "sale": None, "photo": "photos/21.jpg"},
    {"id": 22, "name": "Ethiopian Kibe Butter, 250g", "cat": "Grocery", "price": 210, "sale": 190, "photo": None},
    {"id": 29, "name": "Potatoes, 1kg", "cat": "Grocery", "price": 45, "sale": None, "photo": None},
    {"id": 30, "name": "Carrots, 1kg", "cat": "Grocery", "price": 55, "sale": None, "photo": "photos/30.jpg"},
    {"id": 31, "name": "Cabbage, 1 head", "cat": "Grocery", "price": 40, "sale": None, "photo": None},
    {"id": 32, "name": "Onions, 1kg", "cat": "Grocery", "price": 65, "sale": None, "photo": None},
    {"id": 33, "name": "Garlic, 250g", "cat": "Grocery", "price": 90, "sale": None, "photo": None},
    {"id": 34, "name": "Tomatoes, 1kg", "cat": "Grocery", "price": 70, "sale": 60, "photo": None},
    {"id": 35, "name": "Cooking Oil, 1L", "cat": "Grocery", "price": 260, "sale": None, "photo": None},
    {"id": 50, "name": "Beso, 1kg", "cat": "Grocery", "price": 180, "sale": None, "photo": None},
    {"id": 51, "name": "Aja, 1kg", "cat": "Grocery", "price": 160, "sale": None, "photo": None},
    {"id": 52, "name": "Rice, 1kg", "cat": "Grocery", "price": 220, "sale": None, "photo": None},
    {"id": 53, "name": "Qinche, 1kg", "cat": "Grocery", "price": 170, "sale": None, "photo": None},
    {"id": 54, "name": "Difen Misir, 1kg", "cat": "Grocery", "price": 200, "sale": None, "photo": None},
    {"id": 55, "name": "Split Misir, 1kg", "cat": "Grocery", "price": 210, "sale": None, "photo": None},
    {"id": 56, "name": "Split Ater, 1kg", "cat": "Grocery", "price": 190, "sale": None, "photo": None},
    {"id": 57, "name": "Peanut Butter, 500g", "cat": "Grocery", "price": 280, "sale": None, "photo": None},
    {"id": 49, "name": "Weekly Asbeza", "cat": "Grocery", "price": 950, "sale": None, "photo": None, "builder": True},
    {"id": 23, "name": "Shea Butter Body Cream", "cat": "Beauty & Cosmetics", "price": 240, "sale": None, "photo": None},
    {"id": 24, "name": "Natural Henna Powder, 100g", "cat": "Beauty & Cosmetics", "price": 130, "sale": None, "photo": None},
    {"id": 25, "name": "Matte Lipstick Set", "cat": "Beauty & Cosmetics", "price": 390, "sale": 320, "photo": None},
    {"id": 26, "name": "Voltage Stabilizer, 1000VA", "cat": "Electrical Equipment", "price": 1850, "sale": None, "photo": None},
    {"id": 27, "name": "LED Bulb Pack, 4 x 9W", "cat": "Electrical Equipment", "price": 340, "sale": None, "photo": None},
    {"id": 28, "name": "Rechargeable Emergency Lamp", "cat": "Electrical Equipment", "price": 590, "sale": 480, "photo": None},
    {"id": 38, "name": "Kids Pajama Set, Assorted Prints", "cat": "Apparel", "price": 480, "sale": None, "photo": "photos/38.jpg"},
    {"id": 39, "name": "Kids Pajama Pants, Assorted Prints", "cat": "Apparel", "price": 260, "sale": None, "photo": "photos/39.jpg"},
    {"id": 40, "name": "Girls Leggings, Navy & Lilac", "cat": "Apparel", "price": 320, "sale": None, "photo": "photos/40.jpg"},
    {"id": 41, "name": "Eau de Parfum, For Women", "cat": "Beauty & Cosmetics", "price": 950, "sale": None, "photo": "photos/41.jpg"},
    {"id": 42, "name": "Eau de Parfum, For Men, 50ml", "cat": "Beauty & Cosmetics", "price": 850, "sale": None, "photo": "photos/42.jpg"},
    {"id": 43, "name": "Men's Pullover Hoodie", "cat": "Apparel", "price": 900, "sale": None, "photo": "photos/43.jpg"},
    {"id": 44, "name": "Men's Pique Polo Shirt", "cat": "Apparel", "price": 650, "sale": None, "photo": "photos/44.jpg"},
    {"id": 45, "name": "Men's Boxer Shorts, Assorted Patterns (6-Pack)", "cat": "Apparel", "price": 780, "sale": None, "photo": "photos/45.jpg"},
    {"id": 46, "name": "Personalized Gift Box", "cat": "Gift Packages", "price": 1800, "sale": None, "photo": None,photo": "photos/46.jpg"},
    {"id": 47, "name": "Birthday Gift Box", "cat": "Gift Packages", "price": 2100, "sale": None, "photo": None,photo": "photos/47.jpg"},
    {"id": 48, "name": "Celebration Gift Box", "cat": "Gift Packages", "price": 1950, "sale": None, "photo": None,"photo": "photos/48.jpg"},
]

CATEGORIES = sorted(set(p["cat"] for p in PRODUCTS))
