# Auto-generated from the Dejaf Tadlu website catalog.
# Re-run extract_products.py against index.html any time the site catalog changes,
# or edit this list by hand -- either way keeps the bot and the site in sync.
#
# 'photo' points to a file in the photos/ folder (only present for items with a real
# photo; items without one fall back to text-only display in the bot).
# 'builder' flags interactive website-only features (like the weekly basket builder) --
# the bot sells these as a normal fixed-price item since it can't replicate that UI.

PRODUCTS = [
    {"id": 1, "name": "Yirgacheffe Coffee Beans, 250g", "cat": "Coffee & Tea", "price": 380, "sale": None, "photo": "photos/1.jpg", "builder": False},
    {"id": 18, "name": "Coffee Ceremony Tray Set", "cat": "Coffee & Tea", "price": 980, "sale": None, "photo": None, "builder": False},
    {"id": 36, "name": "Roasted Coffee Beans (የተቆላ ቡና), 250g", "cat": "Coffee & Tea", "price": 400, "sale": None, "photo": "photos/36.jpg", "builder": False},
    {"id": 37, "name": "Ground Coffee (የተፈጨ ቡና), 250g", "cat": "Coffee & Tea", "price": 420, "sale": None, "photo": "photos/37.jpg", "builder": False},
    {"id": 2, "name": "Traditional Clay Jebena", "cat": "Home & Kitchen", "price": 650, "sale": 550, "photo": None, "builder": False},
    {"id": 10, "name": "Electric Injera Mitad", "cat": "Home & Kitchen", "price": 3200, "sale": None, "photo": "photos/10.jpg", "builder": False},
    {"id": 3, "name": "Habesha Kemis, Hand-Embroidered", "cat": "Apparel", "price": 2200, "sale": None, "photo": None, "builder": False},
    {"id": 6, "name": "Handwoven Shemma Scarf", "cat": "Apparel", "price": 480, "sale": None, "photo": None, "builder": False},
    {"id": 11, "name": "Handmade Leather Sandals", "cat": "Apparel", "price": 620, "sale": None, "photo": None, "builder": False},
    {"id": 15, "name": "Habesha Netela, Cotton Shawl", "cat": "Apparel", "price": 900, "sale": None, "photo": None, "builder": False},
    {"id": 4, "name": "Berbere Spice Blend (በርበሬ), 200g", "cat": "Spices & Pantry", "price": 150, "sale": None, "photo": "photos/4.jpg", "builder": False},
    {"id": 5, "name": "Mitmita Spice Blend, 150g", "cat": "Spices & Pantry", "price": 140, "sale": None, "photo": "photos/5.jpg", "builder": False},
    {"id": 7, "name": "Ethiopian Cross Necklace, Silver", "cat": "Jewelry", "price": 950, "sale": 800, "photo": "photos/7.jpg", "builder": False},
    {"id": 9, "name": "Wireless Earbuds", "cat": "Electronics", "price": 2600, "sale": 2100, "photo": "photos/9.jpg", "builder": False},
    {"id": 16, "name": "USB-C Fast Charger, 20W", "cat": "Electronics", "price": 750, "sale": None, "photo": "photos/16.jpg", "builder": False},
    {"id": 13, "name": "Amharic Children's Storybook Set", "cat": "Books & Paper", "price": 260, "sale": None, "photo": None, "builder": False},
    {"id": 14, "name": "Frankincense & Myrrh Set", "cat": "Home & Garden", "price": 180, "sale": None, "photo": None, "builder": False},
    {"id": 17, "name": "Woven Mesob Basket", "cat": "Home & Garden", "price": 1400, "sale": 1150, "photo": None, "builder": False},
    {"id": 19, "name": "Teff Flour, 5kg", "cat": "Grocery", "price": 620, "sale": None, "photo": "photos/19.jpg", "builder": False},
    {"id": 20, "name": "Fresh Avocados, 1kg Bag", "cat": "Grocery", "price": 110, "sale": None, "photo": "photos/20.jpg", "builder": False},
    {"id": 21, "name": "Shiro Powder (ሽሮ), 500g", "cat": "Grocery", "price": 170, "sale": None, "photo": "photos/21.jpg", "builder": False},
    {"id": 22, "name": "Ethiopian Kibe Butter, 250g", "cat": "Grocery", "price": 210, "sale": 190, "photo": None, "builder": False},
    {"id": 29, "name": "Potatoes (ድንች), 1kg", "cat": "Grocery", "price": 45, "sale": None, "photo": None, "builder": False},
    {"id": 30, "name": "Carrots (ካሮት), 1kg", "cat": "Grocery", "price": 55, "sale": None, "photo": "photos/30.jpg", "builder": False},
    {"id": 31, "name": "Cabbage (ጎመን), 1 head", "cat": "Grocery", "price": 40, "sale": None, "photo": None, "builder": False},
    {"id": 32, "name": "Onions (ሽንኩርት), 1kg", "cat": "Grocery", "price": 65, "sale": None, "photo": None, "builder": False},
    {"id": 33, "name": "Garlic (ነጭ ሽንኩርት), 250g", "cat": "Grocery", "price": 90, "sale": None, "photo": None, "builder": False},
    {"id": 34, "name": "Tomatoes (ቲማቲም), 1kg", "cat": "Grocery", "price": 70, "sale": 60, "photo": None, "builder": False},
    {"id": 35, "name": "Cooking Oil (ዘይት), 1L", "cat": "Grocery", "price": 260, "sale": None, "photo": None, "builder": False},
    {"id": 23, "name": "Shea Butter Body Cream", "cat": "Beauty & Cosmetics", "price": 240, "sale": None, "photo": None, "builder": False},
    {"id": 24, "name": "Natural Henna Powder, 100g", "cat": "Beauty & Cosmetics", "price": 130, "sale": None, "photo": None, "builder": False},
    {"id": 25, "name": "Matte Lipstick Set", "cat": "Beauty & Cosmetics", "price": 390, "sale": 320, "photo": None, "builder": False},
    {"id": 26, "name": "Voltage Stabilizer, 1000VA", "cat": "Electrical Equipment", "price": 1850, "sale": None, "photo": None, "builder": False},
    {"id": 27, "name": "LED Bulb Pack, 4 x 9W", "cat": "Electrical Equipment", "price": 340, "sale": None, "photo": None, "builder": False},
    {"id": 28, "name": "Rechargeable Emergency Lamp", "cat": "Electrical Equipment", "price": 590, "sale": 480, "photo": None, "builder": False},
    {"id": 38, "name": "Kids Pajama Set, Assorted Prints", "cat": "Apparel", "price": 480, "sale": None, "photo": "photos/38.jpg", "builder": False},
    {"id": 39, "name": "Kids Pajama Pants, Assorted Prints", "cat": "Apparel", "price": 260, "sale": None, "photo": "photos/39.jpg", "builder": False},
    {"id": 40, "name": "Girls Leggings, Navy & Lilac", "cat": "Apparel", "price": 320, "sale": None, "photo": "photos/40.jpg", "builder": False},
    {"id": 41, "name": "Eau de Parfum, For Women", "cat": "Beauty & Cosmetics", "price": 950, "sale": None, "photo": "photos/41.jpg", "builder": False},
    {"id": 42, "name": "Eau de Parfum, For Men, 50ml", "cat": "Beauty & Cosmetics", "price": 850, "sale": None, "photo": "photos/42.jpg", "builder": False},
    {"id": 43, "name": "Men's Pullover Hoodie", "cat": "Apparel", "price": 900, "sale": None, "photo": "photos/43.jpg", "builder": False},
    {"id": 44, "name": "Men's Pique Polo Shirt", "cat": "Apparel", "price": 650, "sale": None, "photo": "photos/44.jpg", "builder": False},
    {"id": 45, "name": "Men's Boxer Shorts, Assorted Patterns (6-Pack)", "cat": "Apparel", "price": 780, "sale": None, "photo": "photos/45.jpg", "builder": False},
    {"id": 46, "name": "Personalized Gift Box", "cat": "Gift Packages", "price": 1800, "sale": None, "photo": "photos/gift-package-daniel.jpg", "builder": False},
    {"id": 47, "name": "Birthday Gift Box", "cat": "Gift Packages", "price": 2100, "sale": None, "photo": "photos/gift-package-saba.jpg", "builder": False},
    {"id": 48, "name": "Celebration Gift Box", "cat": "Gift Packages", "price": 1950, "sale": None, "photo": "photos/gift-package-daniel.jpg", "builder": False},
    {"id": 49, "name": "ሳምንታዊ አስቤዛ · Weekly Asbeza", "cat": "Grocery", "price": 950, "sale": None, "photo": None, "builder": True},
    {"id": 50, "name": "Beso (በሶ), 1kg", "cat": "Grocery", "price": 180, "sale": None, "photo": None, "builder": False},
    {"id": 51, "name": "Aja (አጃ), 1kg", "cat": "Grocery", "price": 160, "sale": None, "photo": None, "builder": False},
    {"id": 52, "name": "Rice (ሩዝ), 1kg", "cat": "Grocery", "price": 220, "sale": None, "photo": None, "builder": False},
    {"id": 53, "name": "Qinche (ቅንጨ), 1kg", "cat": "Grocery", "price": 170, "sale": None, "photo": None, "builder": False},
    {"id": 54, "name": "Difen Misir (ድፍን ምስር), 1kg", "cat": "Grocery", "price": 200, "sale": None, "photo": None, "builder": False},
    {"id": 55, "name": "Split Misir (ምስር ክክ), 1kg", "cat": "Grocery", "price": 210, "sale": None, "photo": None, "builder": False},
    {"id": 56, "name": "Split Ater (አተር ክክ), 1kg", "cat": "Grocery", "price": 190, "sale": None, "photo": None, "builder": False},
    {"id": 57, "name": "Peanut Butter (የለውዝ ቅቤ), 500g", "cat": "Grocery", "price": 280, "sale": None, "photo": None, "builder": False},
]

CATEGORIES = sorted(set(p['cat'] for p in PRODUCTS))